openapi: 3.0.0
info:
  title: Channel and Post API
  version: 1.0.0
  description: This REST API for creating, managing, and interacting with channels, posts, comments and upvotes.

servers:
- url: http://localhost:5000

paths:
  /channels:
    post:
      summary: Create a channel
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Channel'
      responses:
        '201':
          description: Channel created successfully
          content:
            application/json:
              example:
                message: Channel created successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message:  Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred

    get:
      summary: Get all channels
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string
           
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                channels: [{title: "Channel1", moderator: [...], posts: [...]}, {title: "Channel2", moderator: [...], posts: [...]}, ...]
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message:  Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred

  /channels/{channel_id}:
    get:
      summary: Get details of a specific channel
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string
        - name: channel_id
          in: path
          required: true
          description: ID of the channel
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                title: "Channel1"
                moderator: [...]
                posts: [...]
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message:  Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred
    put:
      summary: Update details of a specific channel
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string
          
        - name: channel_id
          in: path
          required: true
          description: ID of the channel
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Channel'
      responses:
        '200':
          description: Channel updated successfully
          content:
            application/json:
              example:
                message: Channel updated successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message:  Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred

    delete:
      summary: Delete a specific channel
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string
            
        - name: channel_id
          in: path
          required: true
          description: ID of the channel
          schema:
            type: integer
      responses:
        '204':
          description: Channel deleted successfully
          content:
            application/json:
              example:
                message: Channel deleted successfully 
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message:  Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred    

  /channels/{channel_id}/posts:
    get:
      summary: Get all posts in a specific channel
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string

        - name: channel_id
          in: path
          required: true
          description: ID of the channel
          schema:
            type: integer

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                posts:
                  - title: "PostTitle1"
                    content: "<html><body><h1>Hey Guys!</h1> <p>lorem</p></body></html>"
                    upvotes: 10
                    comments: [...]
                    reported: false
                    postId: 1
                    author:
                      name: "John Doe"
                      email: "john.doe@example.com"
                      role: "user"
                    createdAt: "2023-11-13T00:00:00Z"
                    updatedAt: "2023-11-13T12:34:56Z"
                    deletedAt: null
                    tag: [...]

                  - title: "PostTitle2"
                    content: "<html><body><h1>Another Post</h1> <p>lorem ipsum</p></body></html>"
                    upvotes: 5
                    comments: [...]
                    reported: true
                    postId: 2
                    author:
                      name: "Jane Doe"
                      email: "jane.doe@example.com"
                      role: "user"
                    createdAt: "2023-11-14T08:30:00Z"
                    updatedAt: "2023-11-14T09:45:30Z"
                    deletedAt: null
                    tag: [...]
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message:  Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred  

    post:
      summary: Create a post on a specific channel
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string
           
        - name: channel_id
          in: path
          required: true
          description: ID of the channel
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          description: Post created successfully
          content:
            application/json:
              example:
                message: Post created successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message:  Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred

  /channels/{channel_id}/posts/{post_id}:
    get:
      summary: Get details of a specific post in a channel
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string
  
        - name: channel_id
          in: path
          required: true
          description: ID of the channel
          schema:
            type: integer
        - name: post_id
          in: path
          required: true
          description: ID of the post
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                title: "PostTitle"
                content: "<html><body><h1>Hey Guys!</h1> <p>lorem</p></body></html>"
                upvotes: 10
                comments: [...]
                reported: false
                postId: 1
                author: {...}
                createdAt: "2023-11-13T00:00:00Z"
                updatedAt: "2023-11-13T12:34:56Z"
                deletedAt: null
                tag: [...]
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message:  Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred
      

    put:
      summary: Update details of a specific post in a channel
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string
        
        - name: channel_id
          in: path
          required: true
          description: ID of the channel
          schema:
            type: integer
        - name: post_id
          in: path
          required: true
          description: ID of the post
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
          description: Post updated successfully
          content:
            application/json:
              example:
                message: Post updated successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message:  Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred

    delete:
      summary: Delete a specific post in a channel
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string

        - name: channel_id
          in: path
          required: true
          description: ID of the channel
          schema:
            type: integer
        - name: post_id
          in: path
          required: true
          description: ID of the post
          schema:
            type: integer
      responses:
        '204':
          description: Post deleted successfully
          content:
            application/json:
              example:
                message: Post deleted successfully 
             
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message:  Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred

  /channels/{channel_id}/posts/{post_id}/comments:
    get:
      summary: Get all comments on a specific post in a channel
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string
            
        - name: channel_id
          in: path
          required: true
          description: ID of the channel
          schema:
                    type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                comments: [{comment: "Comment1", author: {...}}, {comment: "Comment2", author: {...}}, ...]
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message:  Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred

  /channels/{channel_id}/posts/{post_id}/comments/{comment_id}:
    get:
      summary: Get details of a specific comment on a post in a channel
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string
      
        - name: channel_id
          in: path
          required: true
          description: ID of the channel
          schema:
            type: integer
        - name: post_id
          in: path
          required: true
          description: ID of the post
          schema:
            type: integer
        - name: comment_id
          in: path
          required: true
          description: ID of the comment
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                comment: "CommentContent"
                author: {...}
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message:  Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred

    put:
      summary: Update details of a specific comment on a post in a channel
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string
        
        - name: channel_id
          in: path
          required: true
          description: ID of the channel
          schema:
            type: integer
        - name: post_id
          in: path
          required: true
          description: ID of the post
          schema:
            type: integer
        - name: comment_id
          in: path
          required: true
          description: ID of the comment
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '200':
          description: Comment updated successfully
          content:
            application/json:
              example:
                message: Comment updated successfully
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message:  Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred

    delete:
      summary: Delete a specific comment on a post in a channel
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string

        - name: channel_id
          in: path
          required: true
          description: ID of the channel
          schema:
            type: integer
        - name: post_id
          in: path
          required: true
          description: ID of the post
          schema:
            type: integer
        - name: comment_id
          in: path
          required: true
          description: ID of the comment
          schema:
            type: integer
      responses:
        '204':
          description: Comment deleted successfully
          content:
            application/json:
              example:
                message: Comment deleted successfully 
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message:  Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred

  /channels/{channel_id}/posts/{post_id}/upvotes:
    get:
      summary: Get all upvotes for a specific post in a channel
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string

        - name: channel_id
          in: path
          required: true
          description: ID of the channel
          schema:
            type: integer

        - name: post_id
          in: path
          required: true
          description: ID of the post
          schema:
            type: integer

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                upvotes:
                  - user_id: 1
                    username: "john_doe"
                    upvoted_at: "2023-11-14T12:00:00Z"
                  - user_id: 2
                    username: "jane_doe"
                    upvoted_at: "2023-11-14T12:30:00Z"
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message: Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred
    post:
      summary: Upvote a specific post in a channel
      parameters:
        - name: session
          in: cookie
          description: The session cookie for authentication.
          required: true
          schema:
            type: string

        - name: channel_id
          in: path
          required: true
          description: ID of the channel
          schema:
            type: integer

        - name: post_id
          in: path
          required: true
          description: ID of the post
          schema:
            type: integer

      responses:
        '200':
          description: Upvote successful
          content:
            application/json:
              example:
                message: Upvote successful
        '401':
          description: Unauthorized
          content:
            application/json:
              example:
                error: Unauthorized
                message: Invalid token
        '403':
          description: Forbidden
          content:
            application/json:
              example:
                error: Forbidden
                message: Access Denied
        '500':
          description: Internal Server Error
          content:
            application/json:
              example:
                error: Internal Server Error
                message: An unexpected error occurred

components:
  schemas:
    Channel:
      type: object
      properties:
        title:
          type: string
        moderator:
          type: array
          items:
            $ref: '#/components/schemas/User'
        posts:
          type: array
          items:
            $ref: '#/components/schemas/Post'

    Post:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        upvotes:
          type: integer
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
        reported:
          type: boolean
        postId:
          type: integer
        author:
          $ref: '#/components/schemas/User'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        deletedAt:
          type: string
          format: date-time
        tag:
          type: array
          items:
            type: string

    Comment:
      type: object
      properties:
        comment:
          type: string
        author:
          $ref: '#/components/schemas/User'

    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        role:
          type: string
          enum: ["ADMIN", "STUDENT", "MODERATOR", "AUTHORITY"]
    
    Upvote:
      type: object
      properties:
        user_id:
          type: integer
          description: The ID of the user who upvoted.
        username:
          type: string
          description: The username of the user who upvoted.
        upvoted_at:
          type: string
          format: date-time
          description: The timestamp when the upvote was made.
   

